namespace Maliev.Intranet.Bff.Data;

/// <summary>
/// Persisted record of a quote-accepted alert broadcast to all employees.
/// Each row represents one ProjectQuotationAcceptedEvent received by the BFF.
/// </summary>
public class AlertNotification
{
    /// <summary>Unique alert identifier (generated by the consumer on arrival).</summary>
    public Guid Id { get; set; }

    /// <summary>Stable event idempotency key used to deduplicate quote-accepted bus deliveries.</summary>
    public string EventDeduplicationKey { get; set; } = string.Empty;

    /// <summary>Alert category — always "QuoteAccepted" in this version.</summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>Project identifier from the event payload.</summary>
    public Guid ProjectId { get; set; }

    /// <summary>Human-readable project number, e.g. PRJ-2026-0027.</summary>
    public string ProjectNumber { get; set; } = string.Empty;

    /// <summary>Customer display name. Empty when not available in the event payload.</summary>
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>Number of active parts in this project at acceptance time.</summary>
    public int PartCount { get; set; }

    /// <summary>Comma-separated unique process types, e.g. "CNC, FDM".</summary>
    public string ProcessTypes { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the event arrived at the BFF consumer.</summary>
    public DateTime OccurredAtUtc { get; set; }

    /// <summary>UTC timestamp after which this alert is excluded from all queries (occurred + 7 days).</summary>
    public DateTime ExpiresAtUtc { get; set; }
}
