// Maliev.Intranet.Tests/Client/Components/ThumbnailImageTests.cs
using Bunit;
using Maliev.Intranet.Client.Components.Project;
using Maliev.Intranet.Client.Services;
using Maliev.Intranet.Shared.Dtos;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using MudBlazor;
using Xunit;

namespace Maliev.Intranet.Tests.Client.Components;

public class ThumbnailImageTests : BunitContext
{
    [Fact]
    public void ThumbnailImage_ShowsSkeleton_WhenNotCached()
    {
        Services.AddSingleton(new ThumbnailGenerationService(
            jsRuntime: null!,
            httpClient: new HttpClient(),
            logger: NullLogger<ThumbnailGenerationService>.Instance));

        var component = Render<ThumbnailImage>(parameters => parameters
            .Add(p => p.StoragePath, "path/file.stl")
            .Add(p => p.SignedDownloadUrl, "https://test.com/file.stl"));

        Assert.Contains("thumbnail-pending", component.Markup);
    }

    [Fact]
    public void ThumbnailImage_ShowsImage_WhenCached()
    {
        var service = new ThumbnailGenerationService(
            jsRuntime: null!,
            httpClient: new HttpClient(),
            logger: NullLogger<ThumbnailGenerationService>.Instance);

        var cachedSet = new ThumbnailSetDto { ThumbnailSmall = "data:image/jpeg;base64,abc" };
        service.SetCached("path/file.stl", "v1", cachedSet);

        Services.AddSingleton(service);

        var component = Render<ThumbnailImage>(parameters => parameters
            .Add(p => p.StoragePath, "path/file.stl")
            .Add(p => p.Version, "v1")
            .Add(p => p.SignedDownloadUrl, "https://test.com/file.stl"));

        Assert.Contains("data:image/jpeg;base64,abc", component.Markup);
    }

    [Fact]
    public async Task ThumbnailImage_RefreshesFromCache_WhenAnotherCallerCompletesGeneration()
    {
        // A part uploaded as STEP gets its thumbnails generated by the page-level
        // viewer-GLB pipeline, not by this component (it has no signed URL yet).
        // The component must pick the set up from the shared cache when the
        // Complete progress event arrives.
        var service = new ThumbnailGenerationService(
            jsRuntime: null!,
            httpClient: new HttpClient(),
            logger: NullLogger<ThumbnailGenerationService>.Instance);

        Services.AddSingleton(service);

        var component = Render<ThumbnailImage>(parameters => parameters
            .Add(p => p.StoragePath, "path/file.step")
            .Add(p => p.Version, "v1"));

        Assert.Contains("thumbnail-pending", component.Markup);

        service.SetCached(
            "path/file.step",
            "v1",
            new ThumbnailSetDto { ThumbnailSmall = "data:image/jpeg;base64,fromglb" });
        await service.NotifyAsync(new ThumbnailProgress(
            "path/file.step", ThumbnailGenerationStage.Complete, 100, "Complete"));

        Assert.Contains("data:image/jpeg;base64,fromglb", component.Markup);
    }

    [Fact]
    public async Task ThumbnailImage_IgnoresCompletionEvents_ForOtherStoragePaths()
    {
        var service = new ThumbnailGenerationService(
            jsRuntime: null!,
            httpClient: new HttpClient(),
            logger: NullLogger<ThumbnailGenerationService>.Instance);

        Services.AddSingleton(service);

        var component = Render<ThumbnailImage>(parameters => parameters
            .Add(p => p.StoragePath, "path/file.step")
            .Add(p => p.Version, "v1"));

        service.SetCached(
            "path/other.step",
            "v1",
            new ThumbnailSetDto { ThumbnailSmall = "data:image/jpeg;base64,other" });
        await service.NotifyAsync(new ThumbnailProgress(
            "path/other.step", ThumbnailGenerationStage.Complete, 100, "Complete"));

        Assert.Contains("thumbnail-pending", component.Markup);
        Assert.DoesNotContain("data:image/jpeg;base64,other", component.Markup);
    }

    [Fact]
    public async Task ThumbnailImage_ShowsSpinner_WhenFallbackStage()
    {
        var service = new ThumbnailGenerationService(
            jsRuntime: null!,
            httpClient: new HttpClient(),
            logger: NullLogger<ThumbnailGenerationService>.Instance);

        Services.AddSingleton(service);

        var component = Render<ThumbnailImage>(parameters => parameters
            .Add(p => p.StoragePath, "path/file.stl")
            .Add(p => p.SignedDownloadUrl, "https://test.com/file.stl"));

        await service.NotifyAsync(new ThumbnailProgress(
            "path/file.stl", ThumbnailGenerationStage.Fallback, 0, "Falling back to server"));

        Assert.Contains("thumbnail-fallback", component.Markup);
        Assert.Contains("mud-progress-circular", component.Markup);
        Assert.DoesNotContain(Icons.Material.Outlined.CloudSync, component.Markup);
    }
}
