using Maliev.Aspire.ServiceDefaults.Authorization;
using Maliev.Intranet.Bff.Clients;
using Maliev.Intranet.Shared;
using Microsoft.AspNetCore.Mvc;

namespace Maliev.Intranet.Bff.Controllers;

/// <summary>
/// BFF controller for equipment management operations, proxying to the Facility microservice.
/// Covers equipment lifecycle, notes, loans, maintenance logs, and CNC attachments.
/// </summary>
/// <param name="client">The facility service client.</param>
[ApiController]
[Route("api/[controller]")]
public class EquipmentsController(FacilityServiceClient client) : ControllerBase
{
    // -----------------------------------------------------------------------
    // Equipment CRUD
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves a paged, filtered list of all equipment.
    /// </summary>
    /// <param name="category">Optional category filter (e.g., "FdmPrinter", "CncMachine").</param>
    /// <param name="status">Optional status filter (e.g., "Active", "UnderMaintenance").</param>
    /// <param name="search">Optional search term matching name, brand, or asset code.</param>
    /// <param name="page">Page number (1-based, default 1).</param>
    /// <param name="pageSize">Items per page (default 20).</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A paged response of equipment summaries.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet]
    public async Task<ActionResult<PagedResponse<EquipmentSummaryDto>>> Get(
        [FromQuery] string? category,
        [FromQuery] string? status,
        [FromQuery] string? search,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        CancellationToken ct = default)
    {
        var result = await client.GetEquipmentsAsync(category, status, search, page, pageSize, ct);
        if (result is null)
            return Ok(new PagedResponse<EquipmentSummaryDto>());

        return Ok(new PagedResponse<EquipmentSummaryDto>
        {
            Data = result.Items,
            Meta = new PaginationMeta
            {
                CurrentPage = result.Page,
                PageSize = result.PageSize,
                TotalCount = result.TotalCount,
                TotalItems = result.TotalCount,
                TotalPages = result.PageSize > 0
                    ? (int)Math.Ceiling((double)result.TotalCount / result.PageSize)
                    : 0
            }
        });
    }

    /// <summary>
    /// Retrieves detailed information for a single piece of equipment.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The full equipment detail DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet("{id:guid}")]
    public async Task<ActionResult<EquipmentDetailDto>> GetById(Guid id, CancellationToken ct = default)
    {
        var result = await client.GetEquipmentByIdAsync(id, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    /// <summary>
    /// Registers a new piece of equipment. The asset code is auto-generated by the Facility service.
    /// </summary>
    /// <param name="request">The registration request.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created equipment detail DTO with the generated asset code.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPost]
    public async Task<ActionResult<EquipmentDetailDto>> Register(
        [FromBody] RegisterEquipmentRequest request,
        CancellationToken ct = default)
    {
        var result = await client.RegisterEquipmentAsync(request, ct);
        return result is not null
            ? CreatedAtAction(nameof(GetById), new { id = result.Id }, result)
            : BadRequest();
    }

    /// <summary>
    /// Updates an existing piece of equipment. Requires the current xmin row version.
    /// Returns HTTP 409 on concurrent modification.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment to update.</param>
    /// <param name="request">The update request including the row version for concurrency control.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated equipment detail DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPut("{id:guid}")]
    public async Task<ActionResult<EquipmentDetailDto>> Update(
        Guid id,
        [FromBody] UpdateEquipmentRequest request,
        CancellationToken ct = default)
    {
        var result = await client.UpdateEquipmentAsync(id, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    /// <summary>
    /// Changes the operational status of equipment (e.g., Active → UnderMaintenance).
    /// Invalid status transitions return HTTP 422 from the downstream service.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="request">The status change request including the row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated equipment detail DTO with the new status.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPatch("{id:guid}/status")]
    public async Task<ActionResult<EquipmentDetailDto>> ChangeStatus(
        Guid id,
        [FromBody] ChangeEquipmentStatusRequest request,
        CancellationToken ct = default)
    {
        var result = await client.ChangeEquipmentStatusAsync(id, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    /// <summary>
    /// Hard-deletes equipment. Blocked if job history exists (HTTP 409)
    /// or if JobService is unreachable (HTTP 503).
    /// </summary>
    /// <param name="id">The unique identifier of the equipment to delete.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>HTTP 204 on success.</returns>
    [RequirePermission(MalievPermissions.Facility.Manage, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpDelete("{id:guid}")]
    public async Task<ActionResult> Delete(Guid id, CancellationToken ct = default)
    {
        var success = await client.DeleteEquipmentAsync(id, ct);
        return success ? NoContent() : NotFound();
    }

    // -----------------------------------------------------------------------
    // Notes
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves all notes for a piece of equipment, ordered by creation time ascending.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A list of note DTOs.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet("{id:guid}/notes")]
    public async Task<ActionResult<IReadOnlyList<EquipmentNoteDto>>> GetNotes(
        Guid id,
        CancellationToken ct = default)
    {
        var result = await client.GetNotesAsync(id, ct);
        return Ok(result ?? []);
    }

    /// <summary>
    /// Appends an immutable note to a piece of equipment. Notes cannot be edited or deleted.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="request">The note content.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created note DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPost("{id:guid}/notes")]
    public async Task<ActionResult<EquipmentNoteDto>> AddNote(
        Guid id,
        [FromBody] AddEquipmentNoteRequest request,
        CancellationToken ct = default)
    {
        var result = await client.AddNoteAsync(id, request, ct);
        return result is not null ? Ok(result) : BadRequest();
    }

    // -----------------------------------------------------------------------
    // Loans
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves the loan history for a specific piece of equipment, ordered by start date descending.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A list of loan DTOs.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet("{id:guid}/loans")]
    public async Task<ActionResult<IReadOnlyList<EquipmentLoanDto>>> GetLoans(
        Guid id,
        CancellationToken ct = default)
    {
        var result = await client.GetLoansAsync(id, ct);
        return Ok(result ?? []);
    }

    /// <summary>
    /// Creates a new equipment loan request. Customer loans enter Pending state awaiting approval.
    /// </summary>
    /// <param name="request">The loan request details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created loan DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPost("loans")]
    public async Task<ActionResult<EquipmentLoanDto>> CreateLoan(
        [FromBody] CreateLoanRequest request,
        CancellationToken ct = default)
    {
        var result = await client.CreateLoanAsync(request, ct);
        return result is not null ? Ok(result) : BadRequest();
    }

    /// <summary>
    /// Approves a pending loan request.
    /// For customer loans, triggers generation of the loan agreement PDF.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to approve.</param>
    /// <param name="request">The approval request including approver ID and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO with approved status.</returns>
    [RequirePermission(MalievPermissions.Facility.LoansApprove, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPatch("loans/{loanId:guid}/approve")]
    public async Task<ActionResult<EquipmentLoanDto>> ApproveLoan(
        Guid loanId,
        [FromBody] ApproveLoanRequest request,
        CancellationToken ct = default)
    {
        var result = await client.ApproveLoanAsync(loanId, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    /// <summary>
    /// Rejects a pending loan request.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to reject.</param>
    /// <param name="request">The rejection request including optional reason and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO with rejected status.</returns>
    [RequirePermission(MalievPermissions.Facility.LoansApprove, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPatch("loans/{loanId:guid}/reject")]
    public async Task<ActionResult<EquipmentLoanDto>> RejectLoan(
        Guid loanId,
        [FromBody] RejectLoanRequest request,
        CancellationToken ct = default)
    {
        var result = await client.RejectLoanAsync(loanId, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    /// <summary>
    /// Records the return of equipment from an active loan.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to mark as returned.</param>
    /// <param name="request">The return request including actual return date and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO with returned status.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPatch("loans/{loanId:guid}/return")]
    public async Task<ActionResult<EquipmentLoanDto>> ReturnLoan(
        Guid loanId,
        [FromBody] ReturnLoanRequest request,
        CancellationToken ct = default)
    {
        var result = await client.ReturnLoanAsync(loanId, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }

    // -----------------------------------------------------------------------
    // Maintenance Logs
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves maintenance logs for a specific piece of equipment.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A list of maintenance log DTOs.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet("{id:guid}/maintenance")]
    public async Task<ActionResult<IReadOnlyList<MaintenanceLogDto>>> GetMaintenanceLogs(
        Guid id,
        CancellationToken ct = default)
    {
        var result = await client.GetMaintenanceLogsAsync(id, ct);
        return Ok(result ?? []);
    }

    /// <summary>
    /// Adds a maintenance log entry to a piece of equipment.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="request">The maintenance log details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created maintenance log DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPost("{id:guid}/maintenance")]
    public async Task<ActionResult<MaintenanceLogDto>> AddMaintenanceLog(
        Guid id,
        [FromBody] AddMaintenanceLogRequest request,
        CancellationToken ct = default)
    {
        var result = await client.AddMaintenanceLogAsync(id, request, ct);
        return result is not null ? Ok(result) : BadRequest();
    }

    // -----------------------------------------------------------------------
    // CNC Attachments
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves CNC attachments for a specific piece of equipment.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A list of attachment DTOs.</returns>
    [RequirePermission(MalievPermissions.Facility.Read, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpGet("{id:guid}/attachments")]
    public async Task<ActionResult<IReadOnlyList<EquipmentAttachmentDto>>> GetAttachments(
        Guid id,
        CancellationToken ct = default)
    {
        var result = await client.GetAttachmentsAsync(id, ct);
        return Ok(result ?? []);
    }

    /// <summary>
    /// Adds a CNC attachment to equipment. Only permitted for CncMachine category equipment.
    /// Returns HTTP 422 if the equipment is not a CNC machine.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="request">The attachment details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created attachment DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPost("{id:guid}/attachments")]
    public async Task<ActionResult<EquipmentAttachmentDto>> AddAttachment(
        Guid id,
        [FromBody] AddAttachmentRequest request,
        CancellationToken ct = default)
    {
        var result = await client.AddAttachmentAsync(id, request, ct);
        return result is not null ? Ok(result) : BadRequest();
    }

    /// <summary>
    /// Updates an existing CNC attachment.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="attachmentId">The unique identifier of the attachment to update.</param>
    /// <param name="request">The update request including the row version for concurrency control.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated attachment DTO.</returns>
    [RequirePermission(MalievPermissions.Facility.Write, AuthenticationSchemes = "Bearer,Cookies")]
    [HttpPut("{id:guid}/attachments/{attachmentId:guid}")]
    public async Task<ActionResult<EquipmentAttachmentDto>> UpdateAttachment(
        Guid id,
        Guid attachmentId,
        [FromBody] UpdateAttachmentRequest request,
        CancellationToken ct = default)
    {
        var result = await client.UpdateAttachmentAsync(id, attachmentId, request, ct);
        return result is not null ? Ok(result) : NotFound();
    }
}
