// <auto-generated />
using System;
using Maliev.Intranet.Bff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.Intranet.Bff.Data.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    partial class IntranetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.Intranet.Bff.Data.HealthCheckSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DomainGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("domain_group");

                    b.Property<string>("ErrorBody")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_body");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical");

                    b.Property<string>("LivenessPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("liveness_path");

                    b.Property<double>("LivenessResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("liveness_response_time_ms");

                    b.Property<string>("ReadinessPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("readiness_path");

                    b.Property<double>("ReadinessResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("readiness_response_time_ms");

                    b.Property<string>("RoutePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_prefix");

                    b.Property<DateTime>("SampledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sampled_at_utc");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SampledAtUtc");

                    b.HasIndex("DomainGroup", "SampledAtUtc");

                    b.HasIndex("ServiceName", "SampledAtUtc");

                    b.ToTable("health_check_samples", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
