using System.Net.Http.Json;
using Maliev.Intranet.Shared;

namespace Maliev.Intranet.Bff.Clients;

/// <summary>
/// Client for interacting with the Facility microservice.
/// Covers equipment lifecycle, notes, loans, maintenance logs, and CNC attachments.
/// </summary>
/// <param name="httpClient">The HTTP client instance.</param>
public class FacilityServiceClient(HttpClient httpClient) : IFacilityServiceClient
{
    // -----------------------------------------------------------------------
    // Equipment
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves a paged, filtered list of equipment.
    /// </summary>
    /// <param name="category">Optional category filter (e.g., "FdmPrinter", "CncMachine").</param>
    /// <param name="status">Optional status filter (e.g., "Active", "UnderMaintenance").</param>
    /// <param name="search">Optional search term matching name, brand, or asset code.</param>
    /// <param name="page">Page number (1-based).</param>
    /// <param name="pageSize">Items per page.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A paged result of equipment summaries, or null on failure.</returns>
    public async Task<FacilityPagedResult<EquipmentSummaryDto>?> GetEquipmentsAsync(
        string? category = null,
        string? status = null,
        string? search = null,
        int page = 1,
        int pageSize = 20,
        CancellationToken ct = default)
    {
        var query = BuildEquipmentListQuery(category, status, search, page, pageSize);
        var response = await httpClient.GetAsync($"/facility/v1/equipments{query}", ct);
        if (!response.IsSuccessStatusCode) return null;
        return await response.Content.ReadFromJsonAsync<FacilityPagedResult<EquipmentSummaryDto>>(cancellationToken: ct);
    }

    /// <summary>
    /// Retrieves a single equipment record by ID with full detail and spec data.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The full equipment detail DTO, or null if not found.</returns>
    public async Task<EquipmentDetailDto?> GetEquipmentByIdAsync(Guid id, CancellationToken ct = default)
    {
        return await httpClient.GetFromJsonAsync<EquipmentDetailDto>($"/facility/v1/equipments/{id}", ct);
    }

    /// <summary>
    /// Registers a new piece of equipment. The asset code is auto-generated by the service.
    /// </summary>
    /// <param name="request">The registration request.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created equipment detail DTO, or null on failure.</returns>
    public async Task<EquipmentDetailDto?> RegisterEquipmentAsync(
        RegisterEquipmentRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PostAsJsonAsync("/facility/v1/equipments", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentDetailDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Updates an existing piece of equipment. Requires the current xmin row version.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment to update.</param>
    /// <param name="request">The update request including row version for concurrency control.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated equipment detail DTO, or null on failure.</returns>
    public async Task<EquipmentDetailDto?> UpdateEquipmentAsync(
        Guid id,
        UpdateEquipmentRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PutAsJsonAsync($"/facility/v1/equipments/{id}", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentDetailDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Changes the operational status of equipment (e.g., Active → UnderMaintenance).
    /// Invalid transitions return HTTP 422 from the downstream service.
    /// </summary>
    /// <param name="id">The unique identifier of the equipment.</param>
    /// <param name="request">The status change request including row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated equipment detail DTO, or null on failure.</returns>
    public async Task<EquipmentDetailDto?> ChangeEquipmentStatusAsync(
        Guid id,
        ChangeEquipmentStatusRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PatchAsJsonAsync($"/facility/v1/equipments/{id}/status", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentDetailDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Hard-deletes equipment. Blocked if job history exists (409) or JobService is unreachable (503).
    /// </summary>
    /// <param name="id">The unique identifier of the equipment to delete.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>True if deleted successfully; false otherwise.</returns>
    public async Task<bool> DeleteEquipmentAsync(Guid id, CancellationToken ct = default)
    {
        var response = await httpClient.DeleteAsync($"/facility/v1/equipments/{id}", ct);
        return response.IsSuccessStatusCode;
    }

    // -----------------------------------------------------------------------
    // Notes
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves all notes for a piece of equipment, ordered by creation time ascending.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A read-only list of note DTOs.</returns>
    public async Task<IReadOnlyList<EquipmentNoteDto>?> GetNotesAsync(
        Guid equipmentId,
        CancellationToken ct = default)
    {
        return await httpClient.GetFromJsonAsync<IReadOnlyList<EquipmentNoteDto>>(
            $"/facility/v1/equipments/{equipmentId}/notes", ct);
    }

    /// <summary>
    /// Appends an immutable note to a piece of equipment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="request">The note content.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created note DTO, or null on failure.</returns>
    public async Task<EquipmentNoteDto?> AddNoteAsync(
        Guid equipmentId,
        AddEquipmentNoteRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PostAsJsonAsync(
            $"/facility/v1/equipments/{equipmentId}/notes", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentNoteDto>(cancellationToken: ct)
            : null;
    }

    // -----------------------------------------------------------------------
    // Loans
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves the loan history for a specific piece of equipment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A read-only list of loan DTOs.</returns>
    public async Task<IReadOnlyList<EquipmentLoanDto>?> GetLoansAsync(
        Guid equipmentId,
        CancellationToken ct = default)
    {
        return await httpClient.GetFromJsonAsync<IReadOnlyList<EquipmentLoanDto>>(
            $"/facility/v1/equipments/{equipmentId}/loans", ct);
    }

    /// <summary>
    /// Creates a new equipment loan request.
    /// </summary>
    /// <param name="request">The loan request details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created loan DTO, or null on failure.</returns>
    public async Task<EquipmentLoanDto?> CreateLoanAsync(
        CreateLoanRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PostAsJsonAsync("/facility/v1/loans", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentLoanDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Approves a pending loan request.
    /// For customer loans, triggers a LoanDocumentRequestedEvent to generate the PDF agreement.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to approve.</param>
    /// <param name="request">The approval request including approver ID, borrower display name, and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO, or null on failure.</returns>
    public async Task<EquipmentLoanDto?> ApproveLoanAsync(
        Guid loanId,
        ApproveLoanRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PatchAsJsonAsync($"/facility/v1/loans/{loanId}/approve", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentLoanDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Rejects a pending loan request.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to reject.</param>
    /// <param name="request">The rejection request including optional reason and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO, or null on failure.</returns>
    public async Task<EquipmentLoanDto?> RejectLoanAsync(
        Guid loanId,
        RejectLoanRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PatchAsJsonAsync($"/facility/v1/loans/{loanId}/reject", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentLoanDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Records the return of equipment from an active loan.
    /// </summary>
    /// <param name="loanId">The unique identifier of the loan to mark as returned.</param>
    /// <param name="request">The return request including actual return date and row version.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated loan DTO, or null on failure.</returns>
    public async Task<EquipmentLoanDto?> ReturnLoanAsync(
        Guid loanId,
        ReturnLoanRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PatchAsJsonAsync($"/facility/v1/loans/{loanId}/return", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentLoanDto>(cancellationToken: ct)
            : null;
    }

    // -----------------------------------------------------------------------
    // Maintenance Logs
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves maintenance logs for a specific piece of equipment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A read-only list of maintenance log DTOs.</returns>
    public async Task<IReadOnlyList<MaintenanceLogDto>?> GetMaintenanceLogsAsync(
        Guid equipmentId,
        CancellationToken ct = default)
    {
        return await httpClient.GetFromJsonAsync<IReadOnlyList<MaintenanceLogDto>>(
            $"/facility/v1/equipments/{equipmentId}/maintenance", ct);
    }

    /// <summary>
    /// Adds a maintenance log entry to a piece of equipment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="request">The maintenance log details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created maintenance log DTO, or null on failure.</returns>
    public async Task<MaintenanceLogDto?> AddMaintenanceLogAsync(
        Guid equipmentId,
        AddMaintenanceLogRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PostAsJsonAsync(
            $"/facility/v1/equipments/{equipmentId}/maintenance", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<MaintenanceLogDto>(cancellationToken: ct)
            : null;
    }

    // -----------------------------------------------------------------------
    // CNC Attachments
    // -----------------------------------------------------------------------

    /// <summary>
    /// Retrieves CNC attachments for a specific piece of equipment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A read-only list of attachment DTOs.</returns>
    public async Task<IReadOnlyList<EquipmentAttachmentDto>?> GetAttachmentsAsync(
        Guid equipmentId,
        CancellationToken ct = default)
    {
        return await httpClient.GetFromJsonAsync<IReadOnlyList<EquipmentAttachmentDto>>(
            $"/facility/v1/equipments/{equipmentId}/attachments", ct);
    }

    /// <summary>
    /// Adds a CNC attachment to a piece of equipment (only permitted for CncMachine category).
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="request">The attachment details.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The created attachment DTO, or null on failure.</returns>
    public async Task<EquipmentAttachmentDto?> AddAttachmentAsync(
        Guid equipmentId,
        AddAttachmentRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PostAsJsonAsync(
            $"/facility/v1/equipments/{equipmentId}/attachments", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentAttachmentDto>(cancellationToken: ct)
            : null;
    }

    /// <summary>
    /// Updates an existing CNC attachment.
    /// </summary>
    /// <param name="equipmentId">The unique identifier of the equipment.</param>
    /// <param name="attachmentId">The unique identifier of the attachment to update.</param>
    /// <param name="request">The update request including row version for concurrency control.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The updated attachment DTO, or null on failure.</returns>
    public async Task<EquipmentAttachmentDto?> UpdateAttachmentAsync(
        Guid equipmentId,
        Guid attachmentId,
        UpdateAttachmentRequest request,
        CancellationToken ct = default)
    {
        var response = await httpClient.PutAsJsonAsync(
            $"/facility/v1/equipments/{equipmentId}/attachments/{attachmentId}", request, ct);
        return response.IsSuccessStatusCode
            ? await response.Content.ReadFromJsonAsync<EquipmentAttachmentDto>(cancellationToken: ct)
            : null;
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    private static string BuildEquipmentListQuery(
        string? category,
        string? status,
        string? search,
        int page,
        int pageSize)
    {
        var parts = new List<string>
        {
            $"page={page}",
            $"pageSize={pageSize}"
        };

        if (!string.IsNullOrEmpty(category))
            parts.Add($"category={Uri.EscapeDataString(category)}");

        if (!string.IsNullOrEmpty(status))
            parts.Add($"status={Uri.EscapeDataString(status)}");

        if (!string.IsNullOrEmpty(search))
            parts.Add($"search={Uri.EscapeDataString(search)}");

        return "?" + string.Join("&", parts);
    }
}

/// <summary>
/// Paged result wrapper matching the FacilityService PagedResult shape.
/// Used for deserialising responses from <c>GET /facility/v1/equipments</c>.
/// </summary>
/// <typeparam name="T">The type of items in the result set.</typeparam>
public class FacilityPagedResult<T>
{
    /// <summary>Gets or sets the items on the current page.</summary>
    public IReadOnlyList<T> Items { get; set; } = [];

    /// <summary>Gets or sets the total number of items across all pages.</summary>
    public int TotalCount { get; set; }

    /// <summary>Gets or sets the current page number (1-based).</summary>
    public int Page { get; set; }

    /// <summary>Gets or sets the number of items per page.</summary>
    public int PageSize { get; set; }
}
