using Maliev.Intranet.Shared;

namespace Maliev.Intranet.Bff.Clients;

/// <summary>
/// Client interface for interacting with the Facility microservice.
/// Covers equipment lifecycle, notes, loans, maintenance logs, and CNC attachments.
/// </summary>
public interface IFacilityServiceClient
{
    /// <summary>
    /// Retrieves a paged, filtered list of equipment.
    /// </summary>
    Task<FacilityPagedResult<EquipmentSummaryDto>?> GetEquipmentsAsync(
        string? category = null,
        string? status = null,
        string? search = null,
        int page = 1,
        int pageSize = 20,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves a single equipment record by ID with full detail and spec data.
    /// </summary>
    Task<EquipmentDetailDto?> GetEquipmentByIdAsync(Guid id, CancellationToken ct = default);

    /// <summary>
    /// Registers a new piece of equipment. The asset code is auto-generated by the service.
    /// </summary>
    Task<EquipmentDetailDto?> RegisterEquipmentAsync(
        RegisterEquipmentRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Updates an existing piece of equipment. Requires the current xmin row version.
    /// </summary>
    Task<EquipmentDetailDto?> UpdateEquipmentAsync(
        Guid id,
        UpdateEquipmentRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Changes the operational status of equipment (e.g., Active → UnderMaintenance).
    /// </summary>
    Task<EquipmentDetailDto?> ChangeEquipmentStatusAsync(
        Guid id,
        ChangeEquipmentStatusRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Hard-deletes equipment.
    /// </summary>
    Task<bool> DeleteEquipmentAsync(Guid id, CancellationToken ct = default);

    /// <summary>
    /// Retrieves all notes for a piece of equipment, ordered by creation time ascending.
    /// </summary>
    Task<IReadOnlyList<EquipmentNoteDto>?> GetNotesAsync(
        Guid equipmentId,
        CancellationToken ct = default);

    /// <summary>
    /// Appends an immutable note to a piece of equipment.
    /// </summary>
    Task<EquipmentNoteDto?> AddNoteAsync(
        Guid equipmentId,
        AddEquipmentNoteRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves the loan history for a specific piece of equipment.
    /// </summary>
    Task<IReadOnlyList<EquipmentLoanDto>?> GetLoansAsync(
        Guid equipmentId,
        CancellationToken ct = default);

    /// <summary>
    /// Creates a new equipment loan request.
    /// </summary>
    Task<EquipmentLoanDto?> CreateLoanAsync(
        CreateLoanRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Approves a pending loan request.
    /// </summary>
    Task<EquipmentLoanDto?> ApproveLoanAsync(
        Guid loanId,
        ApproveLoanRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Rejects a pending loan request.
    /// </summary>
    Task<EquipmentLoanDto?> RejectLoanAsync(
        Guid loanId,
        RejectLoanRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Records the return of equipment from an active loan.
    /// </summary>
    Task<EquipmentLoanDto?> ReturnLoanAsync(
        Guid loanId,
        ReturnLoanRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves maintenance logs for a specific piece of equipment.
    /// </summary>
    Task<IReadOnlyList<MaintenanceLogDto>?> GetMaintenanceLogsAsync(
        Guid equipmentId,
        CancellationToken ct = default);

    /// <summary>
    /// Adds a maintenance log entry to a piece of equipment.
    /// </summary>
    Task<MaintenanceLogDto?> AddMaintenanceLogAsync(
        Guid equipmentId,
        AddMaintenanceLogRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves CNC attachments for a specific piece of equipment.
    /// </summary>
    Task<IReadOnlyList<EquipmentAttachmentDto>?> GetAttachmentsAsync(
        Guid equipmentId,
        CancellationToken ct = default);

    /// <summary>
    /// Adds a CNC attachment to a piece of equipment.
    /// </summary>
    Task<EquipmentAttachmentDto?> AddAttachmentAsync(
        Guid equipmentId,
        AddAttachmentRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Updates an existing CNC attachment.
    /// </summary>
    Task<EquipmentAttachmentDto?> UpdateAttachmentAsync(
        Guid equipmentId,
        Guid attachmentId,
        UpdateAttachmentRequest request,
        CancellationToken ct = default);
}

